spring:
  application:
    name: resilience4j
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
resilience4j:
  retry:
    retry-aspect-order: 399 #表示retry的优先级
    backends:
      retryA:
        maxRetryAttempts: 5 #重试次数
        waitDuration: 500 #重试等待时间
        exponentialBackoffMultiplier: 1.1 #间隔乘数
        retryException:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cbA:
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        slidingWindowSize: 2
        recordException:
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 398

